### ISSUE TITLE
0.0.4 crashes

### ISSUE THREAD

**Issue by platinum7919** [muxinc/stats-sdk-exoplayer#3]
Got 2 autounboxing errors in 0.0.4.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
       at com.mux.stats.sdk.core.b.h.d(Unknown Source)
       at com.mux.stats.sdk.core.b.h.a(Unknown Source)
       at com.mux.stats.sdk.core.b.b.handle(Unknown Source)
       at com.mux.stats.sdk.core.a.d.a(Unknown Source)
       at com.mux.stats.sdk.core.c.a(Unknown Source)
       at com.mux.stats.sdk.core.b.b.a(Unknown Source)
       at com.mux.stats.sdk.core.b.g.a(Unknown Source)
       at com.mux.stats.sdk.core.b.g.a(Unknown Source)
       at com.mux.stats.sdk.core.b.b.handle(Unknown Source)
       at com.mux.stats.sdk.core.a.d.a(Unknown Source)
       at com.mux.stats.sdk.core.c.a(Unknown Source)
       at com.mux.stats.sdk.core.b.a(Unknown Source)
       at com.mux.stats.sdk.core.a.a(Unknown Source)
       at com.mux.stats.sdk.muxstats.MuxStats.a(Unknown Source)
       at com.mux.stats.sdk.muxstats.MuxStats.handle(Unknown Source)
       at com.mux.stats.sdk.core.a.d.a(Unknown Source)
       at com.mux.stats.sdk.muxstats.b.o(Unknown Source)
       at com.mux.stats.sdk.muxstats.b.onPlayerStateChanged(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:156)
       at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:510)
       at com.xxxx.yyyy.activity.player.ExoPlayer2Activity.pause(ExoPlayer2Activity.java:1021)
       at com.xxxx.yyyy.activity.player.BasicPlayerActivity.checkAndPlayTrackAtDirection(BasicPlayerActivity.java:1105)
       at com.xxxx.yyyy.activity.player.BasicPlayerActivity.checkAndPlayTrackAtDirection(BasicPlayerActivity.java:1078)
       at com.xxxx.yyyy.activity.player.BasicPlayerActivity.onStateChanged(BasicPlayerActivity.java:1801)
       at com.xxxx.yyyy.activity.player.ExoPlayer2Activity.onPlayerStateChanged(ExoPlayer2Activity.java:679)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:363)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:98)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
and

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
       at com.mux.stats.sdk.core.b.h.c(Unknown Source)
       at com.mux.stats.sdk.core.b.h.a(Unknown Source)
       at com.mux.stats.sdk.core.b.b.handle(Unknown Source)
       at com.mux.stats.sdk.core.a.d.a(Unknown Source)
       at com.mux.stats.sdk.core.c.a(Unknown Source)
       at com.mux.stats.sdk.core.b.b.a(Unknown Source)
       at com.mux.stats.sdk.core.b.g.a(Unknown Source)
       at com.mux.stats.sdk.core.b.b.handle(Unknown Source)
       at com.mux.stats.sdk.core.a.d.a(Unknown Source)
       at com.mux.stats.sdk.core.c.a(Unknown Source)
       at com.mux.stats.sdk.core.b.a(Unknown Source)
       at com.mux.stats.sdk.core.a.a(Unknown Source)
       at com.mux.stats.sdk.muxstats.MuxStats.a(Unknown Source)
       at com.mux.stats.sdk.muxstats.MuxStats.handle(Unknown Source)
       at com.mux.stats.sdk.muxstats.MuxStats.f(Unknown Source)
       at com.mux.stats.sdk.muxstats.MuxStats.a(Unknown Source)
       at com.mux.stats.sdk.muxstats.MuxStats$1.run(Unknown Source)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by theRealWardo** [comment]
Thanks so much for reporting these! Keep them coming!

I'll try to get a fix for these exceptions in the next couple days.

**Comment by jsanford8** [comment]
We just created another release that should address this issue. Please re-open with a new stack trace if you run into this issue again.
